# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23b2a2a875a3354e3edb1e9309d169927034ca7fc01c9dc1beb9df1cb55face4830900d7d329d1db708e244fa29e0dec67bc8039527956b641eebf78b162fa17

test:
  secret_key_base: 6da162cf4477e1f90bcc01e4068283df17f755552cd3f97ef99b55c91e1287b23c266a851758389cbc0b3f6189e93ee08bc4bdc06077798539b152d88f2b4a86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
